CREATE DATABASE IF NOT EXISTS `ICE_PLANT`;

USE `ICE_PLANT`;

CREATE TABLE IF NOT EXISTS `STREAMING_DATA` (
    `TIMESTAMP` 		    VARCHAR(255),
    `TIMESTAMP_RX` 		    LONG,
    `TOPIC`                 VARCHAR(255),
    `NAME`			        VARCHAR(255),
    `VALUE`			        VARCHAR(255)
);