CREATE DATABASE IF NOT EXISTS `ICE_PLANT`;

USE `ICE_PLANT`;

CREATE TABLE IF NOT EXISTS `STREAMING_DATA` (
    `TIMESTAMP`             TIMESTAMP(3),
    `TIMESTAMP_RX` 		    TIMESTAMP(3),
    `TOPIC`                 VARCHAR(255),
    `DEVICE_NAME`           VARCHAR(255),
    `DEVICE_TYPE`			VARCHAR(255),
    `DESCRIPTION`			VARCHAR(255),
    `MEASURE`			    FLOAT,
    `UNIT`			        VARCHAR(255)
);