DROP DATABASE IF EXISTS `ICE_PLANT`;
CREATE DATABASE `ICE_PLANT`;

USE `ICE_PLANT`;

CREATE TABLE `STREAMING_DATA` (
    `TIMESTAMP`             TIMESTAMP(3),
    `TIMESTAMP_RX` 		    TIMESTAMP(3),
    `TOPIC`                 VARCHAR(255),
    `DEVICE_NAME`           VARCHAR(255),
    `DEVICE_TYPE`			VARCHAR(255),
    `DESCRIPTION`			VARCHAR(255),
    `MEASURE`			    FLOAT,
    `UNIT`			        VARCHAR(255)
);

CREATE TABLE `PROCESSED_DATA` (
    `TIMESTAMP_RX`          TIMESTAMP,
    `DEVICE_NAME`           VARCHAR(255),
    `DEVICE_TYPE`			VARCHAR(255),
    `DESCRIPTION`			VARCHAR(255),
    `MAXIMUM_MEASURE`	    FLOAT,
    `MEAN_MEASURE`			FLOAT,
    `MINIMUM_MEASURE`		FLOAT,
    `UNIT`			        VARCHAR(255),
    `BATCH`			        VARCHAR(255),
    PRIMARY KEY             (`TIMESTAMP_RX`, `DEVICE_NAME`, `BATCH`)
);